# -*- coding: utf-8 -*-
"""01_Fundamentos_de_Python_copia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YoRLgemXSHWigk5vPQ2sSwo2O-3dK34x

# **Mis primeros pasos en Python**
"""

# Esta línea de código permite crear variables (Esto es un comentario que Python no va a ejecutar) 3000*50000
x = 18+10

# Consultar la variable guardada previamente
x

# Mostrar mensajes en la pantalla

print("La variable x tiene un valor de",x)

x+15

# Eliminar la variable
del x

x

"""# **Tipo de texto**"""

x = 3.14159

x

type(x)

# float es un valor decimal
# int es un valor entero
# string es un valor de cadena (cualitativa)
# boolean es valor logico dicotomico

# No se pueden crear variables cuyo nombre empiecen por un número
1x = 23

# No se pueden usar palabras reservadas de Python (funciones como del o def) para nombrar a una variable
del = 25

# En python la instrucción de la función print se puede usar varias veces en una celda
print("El valor de x es",x, x+23)
print("El valor de x+8 es",x+8)

y = 45

x+y*x

type(y)

name = "Brian"
lastname = "Alarcon"

type(name)

flag_clientes = True
flag_ingresos = False
flag_infocorp = False

flag_ingresos or flag_infocorp

not flag_clientes

"""# **Operadores matemáticos**"""

45000+3200 #suma

80000-2000 #resta

1900*34 #multiplicación

876/23 #división

2**5 #exponencial

356 == (200+156) #Igualdad

235 != 235 #Desigualdad

# >, <, >=, <= comparación de valores numéricos

"""# **Librerías en Python**"""

# Instalación de librerías
!pip install pandas

!pip install numpy

# Importación de librerías

import pandas as pd

