# -*- coding: utf-8 -*-
"""03_Introducción_a_Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwbKogz0KiRerQhDv-ZrQwge9H-zQ0Fl

# **Introducción a Numpy**
"""

!pip install numpy

import numpy as np

np.__version__

"""# **Array**"""

a = np.array([[0,1,2,3],[4,5,6,7],[8,9,1,0]])

a

m = np.array([range(0,4),range(4,8),range(1,5)])

a.shape # shape permite identificar el numero de filas y columnas (dimensiones)

a.ndim # ndim permite contar los espacios dimensionales de tu arreglo

a.size # size permite contar el número de observaciones que tiene tu arreglo

a.dtype # dtype me indica el tipo de dato que tienen los elementos del arreglo

# arange devuelve valores espaciados uniformemente dentro de un intervalo dado

n = np.arange(1,28,3)

n

# linspace devuelve numeros espaciados uniformemente en un intervalo ya especificado

o = np.linspace(0,4,10)

o

"""# **Arrays Aleatorios**"""

np.random.seed(123) # definición de la semilla aleatoria
w = np.random.rand(10) #vector aleatorio de elementos uniformes entre 0 y 1

w

np.random.rand(10)*2 #vector aleatorio de elementos uniformes entre 0 y 2

np.random.randint(0,100,20)

np.random.randn(15) # vector aleatorio de elementos que cumplan la distribución normal estadística 0,1

"""# **Operaciones con Arrays**"""

x = np.array([1,2,3])
y = np.array([4,5,6])

# Adicion por un valor escalar

x+3

x-3

x*50000

x/23

x+y

x-y

x**2

x**y

x.sum()

np.sum(x)

x.prod()

