# -*- coding: utf-8 -*-
"""04_Introducción_a_la_Lectura_de_Datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VIFjgJboUf3riJKZ-fFJiDfB9u8-RSzF

# **Importando datos**

**1. Data desde la web**
"""

url = "https://raw.githubusercontent.com/JBrianAlicorp/Business-Analytics/master/Data_Analisis_Descriptivo.csv"

url

import pandas as pd

data_web = pd.read_csv(url,encoding="latin1")

data_web.head(6)

data_web.info()

data_web.describe()

"""2. Desde una carpeta local"""

from google.colab import files

uploaded = files.upload()

import io

data_excel = pd.read_excel(io.BytesIO(uploaded["Data_corvina.xlsx"]))

data_excel.head(7)

data_excel.to_excel("data_nueva.xlsx")
files.download("data_nueva.xlsx")

