# -*- coding: utf-8 -*-
"""06_Introducción_a_Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IsVGhrvUvE3aAqShxAN1tstm68z4bYlV

# **Matplotlib**
"""

import matplotlib.pyplot as plt

"""# **Gráfico de línea**"""

a = [1,2,3,4]
b = [11,22,33,44]

plt.plot(a,b)

plt.plot(a,b,"ro")

plt.plot(a,b,"ro")
plt.axis([0,5,0,50]) # plt.axis([xmin,xmax,ymin,ymax])

plt.plot(a,b,color="red")

"""# **Gráfico no lineal**"""

import numpy as np

x = np.linspace(-1,5,20)

x

def f(x):
    return np.exp(-x**2)

f(x)

plt.plot(x,f(x))

plt.plot(x,f(x), marker="o")

plt.plot(x,f(x), marker="o", color = "green")

plt.plot(x,f(x), marker="o", color = "green", linewidth = 5)

plt.plot(x,f(x), marker="o", color = "green", linewidth = 5, markersize = 10)

plt.plot(x,f(x), marker="o", color = "green", linewidth = 5, markersize = 10, linestyle = "--")

plt.plot(x,f(x), marker="o", color = "green", linewidth = 5, markersize = 10, linestyle = "--", label = "f(x)")
plt.legend()

plt.title("Gráfica de la función f(x)")
plt.plot(x,f(x), marker="o", color = "green", linewidth = 5, markersize = 10, linestyle = "--", label = "f(x)")
plt.legend()

plt.title("Gráfica de la función f(x)")
plt.xlabel("Variable 1")
plt.ylabel("Variable 2")
plt.plot(x,f(x), marker="o", color = "green", linewidth = 5, markersize = 10, linestyle = "--", label = "f(x)")
plt.legend()

plt.figure(figsize=(10,5))
plt.title("Gráfica de la función f(x)")
plt.xlabel("Variable 1")
plt.ylabel("Variable 2")
plt.plot(x,f(x), marker="o", color = "green", linewidth = 5, markersize = 10, linestyle = "--", label = "f(x)")
plt.legend()

plt.figure(figsize=(10,5))
plt.title("Gráfica de la función f(x)")
plt.xlabel("Variable 1")
plt.ylabel("Variable 2")
plt.axis((-1,5,-0.5,2.0))
plt.plot(x,f(x), marker="o", color = "green", linewidth = 5, markersize = 10, linestyle = "--", label = "f(x)")
plt.legend()

