# -*- coding: utf-8 -*-
"""11_Introducción_al_Análisis_Exploratorio_de_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AAoaX0LTOIGK380WkH20SuO5Odt8-c_o

## ETAPA 1: Entendimiento contextual del proyecto a desarrollar

En esta etapa debemos plantear el contexto del problema, plantear los objetivos del proyecto y definir las variables y tipos de variables a utilizar
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# Asigno los datos a un dataframe:

url = 'https://raw.githubusercontent.com/JBrianAlicorp/Business-Analytics/master/train.csv'
df_train = pd.read_csv(url,encoding='latin1')
df_train.head(10)

"""### El problema

En la competición de Kaggle 'House prices' se indica que el problema es la predicción del precio de las viviendas, por lo que la variable objetivo es 'SalePrice'. Las demás variables se describen de la siguiente manera:

* <b>MSSubClass</b>: clase de construcción
* <b>MSZoning</b>: clasificación de la zona
* <b>LotFrontage</b>: pies lineales de calle de la parcela
* <b>LotArea</b>: tamaño de la parcela en pies cuadrados
* <b>Street</b>: tipo de acceso por carretera
* <b>Alley</b>: tipo de acceso al callejón
* <b>LotShape</b>: forma de la parcela
* <b>LandContour</b>: planitud de la parcela
* <b>Utilities</b>: servicios públicos disponibles
* <b>LotConfig</b>: Configuración de parcela
* <b>LandSlope</b>: pendiente de la parcela
* <b>Neighborhood</b>: ubicación física dentro de los límites de la ciudad de Ames
* <b>Condition1</b>: proximidad a la carretera principal o al ferrocarril
* <b>Condition2</b>: proximidad a la carretera principal o al ferrocarril (si hay un segundo)
* <b>BldgType</b>: tipo de vivienda
* <b>HouseStyle</b>: estilo de vivienda
* <b>OverallQual</b>: calidad general del material y del acabado
* <b>OverallCond</b>: condición general
* <b>YearBuilt</b>: fecha original de construcción
* <b>YearRemodAdd</b>: fecha de remodelación
* <b>RoofStyle</b>: tipo de cubierta
* <b>RoofMatl</b>: material del techo
* <b>Exterior1st</b>: revestimiento exterior de la casa
* <b>Exterior2nd</b>: revestimiento exterior de la casa (si hay más de un material)
* <b>MasVnrType</b>: tipo de revestimiento de mampostería
* <b>MasVnrArea</b>: área de revestimiento de mampostería en pies cuadrados
* <b>ExterQual</b>: calidad del material exterior
* <b>ExterCond</b>: estado del material en el exterior
* <b>Foundation</b>: tipo de cimentación
* <b>BsmtQual</b>: altura del sótano
* <b>BsmtCond</b>: estado general del sótano
* <b>BsmtExposure</b>: paredes del sótano a nivel de calle o de jardín
* <b>BsmtFinType1</b>: calidad del área acabada del sótano
* <b>BsmtFinSF1</b>: pies cuadrados de la superficie acabada tipo 1
* <b>BsmtFinType2</b>: calidad de la segunda superficie acabada (si existe)
* <b>BsmtFinSF2</b>: Pies cuadrados de la superficie acabada tipo 2
* <b>BsmtUnfSF</b>: pies cuadrados del área sin terminar del sótano
* <b>TotalBsmtSF</b>: pies cuadrados totales del sótano
* <b>Heating</b>: tipo de calefacción
* <b>HeatingQC</b>: calidad y estado de la calefacción
* <b>CentralAir</b>: aire acondicionado central
* <b>Electrical</b>: sistema eléctrico
* <b>1erFlrSF</b>: área en pies cuadrados de la primera planta (o planta baja)
* <b>2ndFlrSF</b>: área en pies cuadrados de la segunda planta
* <b>LowQualFinSF</b>: pies cuadrados acabados de baja calidad (todos los pisos)
* <b>GrLivArea</b>: superficie habitable por encima del nivel del suelo en pies cuadrados
* <b>BsmtFullBath</b>: cuartos de baño completos en el sótano
* <b>BsmtHalfBath</b>: medio baño del sótano
* <b>FullBath</b>: baños completos sobre el nivel del suelo
* <b>HalfBath</b>: medios baños sobre el nivel del suelo
* <b>Bedroom</b>: número de dormitorios por encima del nivel del sótano
* <b>Kitchen</b>: número de cocinas
* <b>KitchenQual</b>: calidad de la cocina
* <b>TotRmsAbvGrd</b>: total de habitaciones por encima del nivel del suelo (no incluye baños)
* <b>Functional</b>: valoración de la funcionalidad de la vivienda
* <b>Fireplaces</b>: número de chimeneas
* <b>FireplaceQu</b>: calidad de la chimenea
* <b>GarageType</b>: ubicación del garaje
* <b>GarageYrBlt</b>: año de construcción del garaje
* <b>GarageFinish</b>: acabado interior del garaje
* <b>GarageCars</b>: tamaño del garaje en capacidad de coches
* <b>GarageArea</b>: tamaño del garaje en pies cuadrados
* <b>GarageQual</b>: calidad de garaje
* <b>GarageCond</b>: condición de garaje
* <b>PavedDrive</b>: calzada asfaltada
* <b>WoodDeckSF</b>: area de plataforma de madera en pies cuadrados
* <b>OpenPorchSF</b>: área de porche abierto en pies cuadrados
* <b>EnclosedPorch</b>: área de porche cerrada en pies cuadrados
* <b>3SsnPorch</b>: área de porche de tres estaciones en pies cuadrados
* <b>ScreenPorch</b>: superficie acristalada del porche en pies cuadrados
* <b>PoolArea</b>: área de la piscina en pies cuadrados
* <b>PoolQC</b>: calidad de la piscina
* <b>Fence</b>: calidad de la valla
* <b>MiscFeature</b>: característica miscelánea no cubierta en otras categorías
* <b>MiscVal</b>: valor en dólares de la característica miscelánea
* <b>MoSold</b>: mes de venta
* <b>YrSold</b>: año de venta
* <b>SaleType</b>: tipo de venta
* <b>SaleCondition</b>: Condiciones de venta

"""

df_train.info()

"""Podemos observar que hay variables con casi el 100% de valores nulos, esas variables no deberían considerarse en nuestro análisis.

## ETAPA 2: Preparación y valor agregado de los datos

En esta etapa revisaremos la data y la estructura de la información
"""

df_train.shape

# Echo un vistazo las columnas:

df_train.columns

df_train.head(20)

df_train[['Alley','PoolQC','Fence','MiscFeature']]

### hay que elminar variables con gran cantidad de nulos (>90%)
df_train = df_train.drop(columns = ['Alley','PoolQC','Fence','MiscFeature'])

# guardamos un backup de la base
df_train_bk = df_train

# eliminamos la variable identificadora de la base
df_train = df_train.drop(columns = ['Id'])

"""En este caso no hay más configuraciones que hacer en la tabla de trabajo. Ya habiendo retirados esos campos con muchos valores nulos continuaremos con el análisis descriptivo.

## ETAPA 3 : Examen gráfico y descriptivo numérico

### Análisis univariado: 'SalePrice'

La variable 'SalePrice' es la variable objetivo de este conjunto de datos. En pasos posteriores a este análisis exploratorio de datos se realizaría una predicción del valor de esta variable, por lo que voy a estudiarla con mayor detenimiento:
"""

# Resumen de estadística descriptiva:

df_train['SalePrice'].describe()

# Histograma con seaborn:

sns.distplot(df_train['SalePrice'])
plt.show()

# Histograma con pandas:

df_train['SalePrice'].plot(kind='hist',density=True, edgecolor = 'k')
plt.show()

# Diagrama de cajas:

df_train['SalePrice'].plot(kind='box')
plt.show()

"""A simple vista se pueden apreciar:

* Una desviación con respecto a la distribución normal.
* Una asimetría positiva.
* Algunos picos.
* Varios posibles datos atípicos

Para una variable objetivo cualitativa

* Hacer tablas de frecuencia (usando pandas group by)
* Revisar la magnitud de la categoría de éxito (si es muy pequeño deberiamos muestrear)
* Graficos recomendados circulares y grafico de barras (barplot)

Si no hay variable objetivo, esta parta no se hace. Se realiza en este caso lo siguiente:

* Revisión del problema y objetivos
* Tipos de datos.
* Revisión de nulos y atípicos

### Revisando las variables explicactivas cuantitativas:
"""

# extraemos las variables cuantitativas, quitando las variables Id
list(df_train.describe().columns)

# describe solo sirve en un dataframe para variables cuantitantiva
# si se usa en una cualitativa de manera directa, saca una tabla de frecuencia

lista_cuantitativas = list(df_train.describe().columns)
lista_cuantitativas

# realizamos histogramas para revisar la distribución de cada variable cuantitativa
for var in lista_cuantitativas:
    df_train[var].plot(kind='hist', title=var, bins=30)
    plt.show()

# realizamos diagramas de cajas para revisar la distribución de cada variable cuantitativa
for var in lista_cuantitativas:
    df_train[var].plot(kind='box', title=var)
    plt.show()

"""Con estos gráficos podemos revisar la distribución de la variables cuantitativas y posibles outliers por variables.

### Revisando las variables explicactivas cualitativas:
"""

# extraemos las listas de cuantitativas
lista_cuantitativas = list(df_train.describe().columns)

#ahora en la base total quitamos estas variables, quedandonos con las cualitativas
lista_cualitativas = df_train.drop(columns = lista_cuantitativas).columns
lista_cualitativas

df_train[lista_cualitativas]

# realizamos diagramas de barras para revisar la distribución de frecuencias de cada variable cualitativa
for var in lista_cualitativas:
    df_train.groupby(var)['SalePrice'].count().plot.bar()
    plt.show()

"""En este punto debemos revisar las variables que sólo tengan una categoría relevante y cuestionar si dejarlas o no para continuar nuestros análisis.

### Relación con variables numéricas
"""

# Diagrama de dispersión cada variable con la variable objetivo (saleprice):

lista_cuantitativas = list(df_train.describe().columns)
for var in lista_cuantitativas:
    print(np.corrcoef(df_train['SalePrice'], df_train[var]))
    data = pd.concat([df_train['SalePrice'], df_train[var]], axis=1)
    data.plot.scatter(x=var, y='SalePrice', alpha = 0.5)
    plt.show()

"""**¿Qué podemos ver en estos gráficos?**

* Relaciones entre la variable cuantitativa de inetrés con cada una de las demás, además de su coeficiente de correlación.
* Si hay variables relacionadas donde haya sesgo con alguno de los extremos, lo que podría lllevar a eliminarla.
* Eliminar variables poco correlacionadas para descartarlas.
* Si vemos una relación con una variable discreta podemos revisarla con el siguiente gráfico para más detalle.
"""

# Diagrama de cajas Fullbath/saleprice:

var = 'FullBath'
data = pd.concat([df_train['SalePrice'], df_train[var]], axis=1)
f, ax = plt.subplots(figsize=(8, 6))
fig = sns.boxplot(x=var, y="SalePrice", data=data)
fig.axis(ymin=0, ymax=800000)
plt.show()

# Diagrama de cajas GarageCars/saleprice:

var = 'GarageCars'
data = pd.concat([df_train['SalePrice'], df_train[var]], axis=1)
f, ax = plt.subplots(figsize=(8, 6))
fig = sns.boxplot(x=var, y="SalePrice", data=data)
fig.axis(ymin=0, ymax=800000)
plt.show()

# Diagrama de cajas Years/saleprice:

var = 'YearBuilt'
data = pd.concat([df_train['SalePrice'], df_train[var]], axis=1)
f, ax = plt.subplots(figsize=(8, 6))
fig = sns.boxplot(x=var, y="SalePrice", data=data)
fig.axis(ymin=0, ymax=800000)
plt.show()

"""En este caso vemos que puede haber una relación significativa entre el FullBath y SalesPrice

### Relación de variables cuantitativas con variables categóricas

Sirve para variables Target u objetivo cuantitativas y cualitativa
"""

# Diagrama de cajas overallqual/saleprice:
var = 'OverallQual'
data = pd.concat([df_train['SalePrice'], df_train[var]], axis=1)
f, ax = plt.subplots(figsize=(8, 6))
fig = sns.boxplot(x=var, y="SalePrice", data=data)
fig.axis(ymin=0, ymax=800000)
plt.show()

# Diagrama de cajas RoofMatl/saleprice:
for var in lista_cualitativas:
    data = pd.concat([df_train['SalePrice'], df_train[var]], axis=1)
    f, ax = plt.subplots(figsize=(16, 8))
    fig = sns.boxplot(x=var, y="SalePrice", data=data)
    fig.axis(ymin=0, ymax=800000)
    plt.xticks(rotation=90)
    plt.show()

"""### Resumiendo:

* 'GrLivArea' y 'TotalBsmtSF' mantienen una relación lineal positiva con 'SalePrice', aumentando en el mismo sentido. En el caso de 'TotalBsmtSF', la pendiente de esta relación es muy acentuada.
* 'OverallQual' y 'YearBuilt' también parecen relacionadas con 'SalePrice' (más fuerte en el primer caso), tal y como se puede observar en los diagramas de cajas.

Sólo he explorado cuatro variables, pero hay muchas otras a analizar.

### Relación de variables categóricas o cualitativas

Sirve para variables Target cualitativa

Asumiendo que la variable CentralAir es la variable target cualitativa.
Validaremos si PavedDrive es significaiva
"""

pd.crosstab(df_train['PavedDrive'],df_train['CentralAir'])

cruce = pd.crosstab(df_train['PavedDrive'],df_train['CentralAir'],margins = True,normalize = 'index')
cruce

cruce.plot.bar(stacked = True)
plt.show()

"""Como vemos diferencias entre la proporción de la variable de interés en cada categoría a diferencia del total, se puede afirmar que la variable PavedDrive afecta a la variable "obejetivo" CentalAir"

## ETAPA 4: Asociaciones Cualitativas y Cuantitativas

### Análisis multivariado

Hasta ahora sólo me he dejado llevar por la intuición para el análisis de las variables que he creído importantes. Es hora de un análisis más objetivo.

Para ello voy a realizar las siguientes pruebas de correlación:
* Matriz de correlación general.
* Matriz de correlación centrada en la variable 'SalePrice'.
* Diagramas de dispersión entre las variables más correladas.

#### Matriz de correlación (en forma de mapa de calor)
"""

# Matriz de correlación:

corrmat = df_train.corr()
f, ax = plt.subplots(figsize=(12, 9))
sns.heatmap(corrmat, vmax=.8, square=True)
plt.show()

"""El mapa de calor es una forma visual muy útil para para conocer las variables y sus relaciones. A primera vista hay dos variables que llaman la atención: 'TotalBsmtSF' y '1stFlrSF', seguidas por las variables 'Garage*X*'. En ambos casos parece haber una correlación significativa; en realidad es tan fuerte que podría indicar multicolinealidad, es decir, que básicamente ofrecen la misma información.

Con respecto a las correlaciones de la variable 'SalePrice', destacan las vistas anteriormente ('GrLivArea', 'TotalBsmtSF' y 'OverallQual'), pero hay otras que también deberían ser tenidas en cuenta.

#### Matriz de correlación de 'SalePrice'
"""

# Matriz de correlación
k = 10 # Número de variables.
cols = corrmat.nlargest(k, 'SalePrice')['SalePrice'].index
cm = np.corrcoef(df_train[cols].values.T)
sns.set(font_scale = 1.25)
hm = sns.heatmap(cm, cbar = True, annot = True, square = True, fmt = '.2f', annot_kws = {'size': 10}, yticklabels = cols.values, xticklabels = cols.values)
plt.show()

corr = df_train.corr()
corr[['SalePrice']].sort_values(by = 'SalePrice',ascending = False).style.background_gradient()

"""En estas matrices de correlación se puede observar:

* 'OverallQual', 'GrLivArea' y 'TotalBsmtSF' están fuertemente correladas con 'SalePrice'.
* 'GarageCars' y 'GarageArea' también están fuertemente correladas pero, como he comentado anteriormente, el número de coches que se pueden aparcar en un garaje es una consecuencia de su superficie. Es por esto que sólo voy a mantener una de estas variables en el análisis, 'GarageCars', ya que está más correlada con 'SalePrice'.
* 'TotalBsmtSF' y '1stFloor' plantean la misma situación. En este caso mantendré 'TotalBsmtSF'.
* 'FullBath' también está correlada con 'SalePrice'. Parece que a la gente le gusta darse un baño en casa...
* 'TotRmsAbvGrd' y 'GrLivArea', otro caso de multicolinealidad.
* 'YearBuilt' también está ligeramente correlada con 'SalePrice'.

#### Diagramas de dispersión entre 'SalePrice' y sus variables correlacionadas
"""

# Scatter plot:

sns.set()
cols = ['SalePrice', 'OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF', 'FullBath', 'YearBuilt']
sns.pairplot(df_train[cols], size = 2.5)
plt.show();

cols = ['SalePrice', 'OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF', 'FullBath', 'YearBuilt']
pd.plotting.scatter_matrix(df_train[cols], diagonal='kde', figsize = (20,20))
plt.show()

"""Aunque ya habíamos visto algunas de las figuras, este diagrama nos facilita una comprensión general sobre las relaciones entre las variables."""