# -*- coding: utf-8 -*-
"""12_Caso_1_EDA_en_HR_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181OFlhy2oFyDzuWidHEYluyDo5zvUZin

# **Análisis Exploratorio de Datos en Recursos Humanos**
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import io

from google.colab import files

uploaded = files.upload()

data = pd.read_csv(io.BytesIO(uploaded["HR_comma_sep.csv"]),encoding="latin-1", sep=",")

data.head(8)

data.info()

# Renombrar el nombre de la columna sale por department

data.rename(columns={"sales":"department"}, inplace = True)

data.head()

# Convertir la variable salary en una variable numérica

data["salary"].value_counts()

# Label encoding

data["salary"] = data["salary"].map({"low":1,"medium":2,"high":3})

data.head()

data.describe()

# ¿Cuántos colaboradores trabajan en cada área de la empresa?

data["department"].value_counts(normalize=True)*100

#¿cuál es la distribución salarial de colaboradores según rango?

data["salary"].value_counts()

#¿Cuántos empleados tengo por rango salarial y departamento?

table = data.pivot_table(values="satisfaction_level", index = "department", columns = "salary", aggfunc = np.count_nonzero)
table

sns.boxplot(x="satisfaction_level", data=data, orient="v")

sns.boxplot(x="last_evaluation", data=data, orient="v")

sns.boxplot(x="number_project", data=data, orient="v")

sns.boxplot(x="average_montly_hours", data=data, orient="v")

sns.boxplot(x="time_spend_company", data=data, orient="v")

# Análisis correlacional

corr = data.corr()

corr

sns.heatmap(corr, annot=True)

"""# **Hipótesis a validar**"""

# ¿Cuántos colaboradores se fueron de la compañía?

print(data["left"].value_counts()[1],"colaboradores se fueron de la empresa")

sns.countplot(data.left)

# El salario es una razón por la cual los colaboradores dejan la compañía

a = sns.factorplot(x="salary",y="left",kind="bar",data=data)
plt.title("Colaboradores que dejaron la empresa según rango salarial")
a.set_xticklabels(["Low","Medium","High"])

# El salario tiene relación con el área donde trabaja el colaborador

b = sns.factorplot(x="salary",hue="department",kind="count",data=data,size=5)
plt.title("Salarios por área")
b.set_xticklabels(["Low","Medium","High"])

# Es peligroso el trabajo y es una razón para dejar la empresa?

sns.factorplot(x="Work_accident",y="left",kind="bar",data=data)

# Performance Analysis: Comparar el valor de la evaluación entre colaboradores que se fueron y no se fueron de la compañía

plt.figure(figsize=(7,7))
bins = np.linspace(0.305,1.0001, 14)
plt.hist(data[data["left"]==1]["last_evaluation"], bins=bins, alpha = 1, label="Colaboradores que se fueron")
plt.hist(data[data["left"]==0]["last_evaluation"], bins=bins, alpha = 0.5, label="Colaboradores que no se fueron")
plt.title("Performance de colaboradores")
plt.legend()

